development:
  sessions:
    default:
      database: nata3allam_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: nata3allam_testing
      hosts:
        - localhost:27017

staging:
  sessions:
    default:
      database: nata3allam_staging
      hosts:
        - localhost:27017